In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#0-D array
import numpy as np
arr = np.array(42)
print(arr)

42


In [6]:
#1-D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [12]:
#2-D array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
#3-D array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [14]:
#ndim attribute(defining dimension)

import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


In [17]:
#access array elements/array indexing

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1])
print(arr[0])

2
1


In [18]:
#add 3rd and 4th index

import numpy as np
arr = np.array([1,2,3,4])
print(arr[3]+arr[2])


7


In [20]:
#access 2-D arrays

import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("2nd element of 1st row:",arr[0,1])
print("3rd element of 2nd row:",arr[1,2])

2nd element of 1st row: 2
3rd element of 2nd row: 6


In [21]:
#slicing

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,])
print(arr[1:5])

[2 3 4 5]


In [22]:
#slicing(w/o start index)

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,])
print(arr[:7])

[1 2 3 4 5 6 7]


In [23]:
#slicing(both start and end not mentioned)

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,])
print(arr[:])

[1 2 3 4 5 6 7 8]


In [24]:
#slicing(end not mentioned)

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,])
print(arr[2:])

[3 4 5 6 7 8]


In [ ]:
#slicing

import numpy as np

In [29]:
#slicing(negatice)

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[-3:-1])


[6 7]


In [30]:
#slicing(bichke 2)

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5:2])

[2 4]


In [36]:
#slicing(every other element from entire array)

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[::2])
print(arr[::3])
print(arr[2::3])

[1 3 5 7]
[1 4 7]
[3 6]


In [2]:
#slicing 2d array

import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [3]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0, 1:4])

[2 3 4]


In [10]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
element = arr[1,2]
print(element)


6


In [11]:
#slicing a row
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_slice=arr[0:2,:]
print(row_slice)

[[1 2 3]
 [4 5 6]]


In [12]:
slicing a column
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
col_slice=arr[:,1:3]
print(col_slice)

[[2 3]
 [5 6]
 [8 9]]
